### PR TITLE
Patch 132

### PR DESCRIPTION
**Pull request by quantum9Innovation**
Epispot now supports built-in parameter distributions, see: #132 for more.
**Work is still being done on: #135, #134*

### CODE REVIEW

**Comment by quantum9Innovation** [comment]
@Quantalabs we need a review on the following issues that are holding up the merge:
- Spellcheck (should we keep it?)
- Code coverage (when is a good time to implement testing? now? v3-stable?)

**Review by Quantalabs — APPROVED** [review]
LGTM

**Comment by Quantalabs** [comment]
> @Quantalabs we need a review on the following issues that are holding up the merge:
> 
> * Spellcheck (should we keep it?)
> * Code coverage (when is a good time to implement testing? now? v3-stable?)

1) No.
2) Stable version

**Comment by quantum9Innovation** [comment]
> > @Quantalabs we need a review on the following issues that are holding up the merge:
> > 
> > * Spellcheck (should we keep it?)
> > * Code coverage (when is a good time to implement testing? now? v3-stable?)
> 
> 1. No.
> 2. Stable version

Ok, merging the PR now and then submitting a new one to get rid of spellcheck. Testing will arrive if we have time or may result in postponing the release date for epispot v3.

**Pull request merged**
